// Copyright 2017 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
package v1alpha1

import (
	time "time"

	ianlewis_org_v1alpha1 "github.com/ianlewis/memcached-operator/internal/apis/ianlewis.org/v1alpha1"
	versioned "github.com/ianlewis/memcached-operator/internal/client/clientset/versioned"
	internalinterfaces "github.com/ianlewis/memcached-operator/internal/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ianlewis/memcached-operator/internal/client/listers/ianlewis.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// MemcachedClusterInformer provides access to a shared informer and lister for
// MemcachedClusters.
type MemcachedClusterInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MemcachedClusterLister
}

type memcachedClusterInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewMemcachedClusterInformer constructs a new informer for MemcachedCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMemcachedClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredMemcachedClusterInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredMemcachedClusterInformer constructs a new informer for MemcachedCluster type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredMemcachedClusterInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IanlewisV1alpha1().MemcachedClusters(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.IanlewisV1alpha1().MemcachedClusters(namespace).Watch(options)
			},
		},
		&ianlewis_org_v1alpha1.MemcachedCluster{},
		resyncPeriod,
		indexers,
	)
}

func (f *memcachedClusterInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredMemcachedClusterInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *memcachedClusterInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ianlewis_org_v1alpha1.MemcachedCluster{}, f.defaultInformer)
}

func (f *memcachedClusterInformer) Lister() v1alpha1.MemcachedClusterLister {
	return v1alpha1.NewMemcachedClusterLister(f.Informer().GetIndexer())
}
