// Copyright 2017 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.

// This file was automatically generated by informer-gen

package v1alpha1

import (
	ianlewis_org_v1alpha1 "github.com/ianlewis/memcached-operator/pkg/apis/ianlewis.org/v1alpha1"
	versioned "github.com/ianlewis/memcached-operator/pkg/client/clientset/versioned"
	internalinterfaces "github.com/ianlewis/memcached-operator/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/ianlewis/memcached-operator/pkg/client/listers/ianlewis/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
	time "time"
)

// MemcachedProxyInformer provides access to a shared informer and lister for
// MemcachedProxies.
type MemcachedProxyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.MemcachedProxyLister
}

type memcachedProxyInformer struct {
	factory internalinterfaces.SharedInformerFactory
}

// NewMemcachedProxyInformer constructs a new informer for MemcachedProxy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewMemcachedProxyInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				return client.IanlewisV1alpha1().MemcachedProxies(namespace).List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				return client.IanlewisV1alpha1().MemcachedProxies(namespace).Watch(options)
			},
		},
		&ianlewis_org_v1alpha1.MemcachedProxy{},
		resyncPeriod,
		indexers,
	)
}

func defaultMemcachedProxyInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewMemcachedProxyInformer(client, v1.NamespaceAll, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc})
}

func (f *memcachedProxyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&ianlewis_org_v1alpha1.MemcachedProxy{}, defaultMemcachedProxyInformer)
}

func (f *memcachedProxyInformer) Lister() v1alpha1.MemcachedProxyLister {
	return v1alpha1.NewMemcachedProxyLister(f.Informer().GetIndexer())
}
