// Copyright 2017 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
package v1alpha1

import (
	v1alpha1 "github.com/ianlewis/memcached-operator/internal/apis/ianlewis.org/v1alpha1"
	scheme "github.com/ianlewis/memcached-operator/internal/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MemcachedClustersGetter has a method to return a MemcachedClusterInterface.
// A group's client should implement this interface.
type MemcachedClustersGetter interface {
	MemcachedClusters(namespace string) MemcachedClusterInterface
}

// MemcachedClusterInterface has methods to work with MemcachedCluster resources.
type MemcachedClusterInterface interface {
	Create(*v1alpha1.MemcachedCluster) (*v1alpha1.MemcachedCluster, error)
	Update(*v1alpha1.MemcachedCluster) (*v1alpha1.MemcachedCluster, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MemcachedCluster, error)
	List(opts v1.ListOptions) (*v1alpha1.MemcachedClusterList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MemcachedCluster, err error)
	MemcachedClusterExpansion
}

// memcachedClusters implements MemcachedClusterInterface
type memcachedClusters struct {
	client rest.Interface
	ns     string
}

// newMemcachedClusters returns a MemcachedClusters
func newMemcachedClusters(c *IanlewisV1alpha1Client, namespace string) *memcachedClusters {
	return &memcachedClusters{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the memcachedCluster, and returns the corresponding memcachedCluster object, and an error if there is any.
func (c *memcachedClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.MemcachedCluster, err error) {
	result = &v1alpha1.MemcachedCluster{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("memcachedclusters").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MemcachedClusters that match those selectors.
func (c *memcachedClusters) List(opts v1.ListOptions) (result *v1alpha1.MemcachedClusterList, err error) {
	result = &v1alpha1.MemcachedClusterList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("memcachedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested memcachedClusters.
func (c *memcachedClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("memcachedclusters").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a memcachedCluster and creates it.  Returns the server's representation of the memcachedCluster, and an error, if there is any.
func (c *memcachedClusters) Create(memcachedCluster *v1alpha1.MemcachedCluster) (result *v1alpha1.MemcachedCluster, err error) {
	result = &v1alpha1.MemcachedCluster{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("memcachedclusters").
		Body(memcachedCluster).
		Do().
		Into(result)
	return
}

// Update takes the representation of a memcachedCluster and updates it. Returns the server's representation of the memcachedCluster, and an error, if there is any.
func (c *memcachedClusters) Update(memcachedCluster *v1alpha1.MemcachedCluster) (result *v1alpha1.MemcachedCluster, err error) {
	result = &v1alpha1.MemcachedCluster{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("memcachedclusters").
		Name(memcachedCluster.Name).
		Body(memcachedCluster).
		Do().
		Into(result)
	return
}

// Delete takes name of the memcachedCluster and deletes it. Returns an error if one occurs.
func (c *memcachedClusters) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("memcachedclusters").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *memcachedClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("memcachedclusters").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched memcachedCluster.
func (c *memcachedClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MemcachedCluster, err error) {
	result = &v1alpha1.MemcachedCluster{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("memcachedclusters").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
