// Copyright 2017 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT EDIT DIRECTLY.
package fake

import (
	v1alpha1 "github.com/ianlewis/memcached-operator/internal/apis/ianlewis.org/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMemcachedClusters implements MemcachedClusterInterface
type FakeMemcachedClusters struct {
	Fake *FakeIanlewisV1alpha1
	ns   string
}

var memcachedclustersResource = schema.GroupVersionResource{Group: "ianlewis.org", Version: "v1alpha1", Resource: "memcachedclusters"}

var memcachedclustersKind = schema.GroupVersionKind{Group: "ianlewis.org", Version: "v1alpha1", Kind: "MemcachedCluster"}

// Get takes name of the memcachedCluster, and returns the corresponding memcachedCluster object, and an error if there is any.
func (c *FakeMemcachedClusters) Get(name string, options v1.GetOptions) (result *v1alpha1.MemcachedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(memcachedclustersResource, c.ns, name), &v1alpha1.MemcachedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemcachedCluster), err
}

// List takes label and field selectors, and returns the list of MemcachedClusters that match those selectors.
func (c *FakeMemcachedClusters) List(opts v1.ListOptions) (result *v1alpha1.MemcachedClusterList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(memcachedclustersResource, memcachedclustersKind, c.ns, opts), &v1alpha1.MemcachedClusterList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MemcachedClusterList{}
	for _, item := range obj.(*v1alpha1.MemcachedClusterList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested memcachedClusters.
func (c *FakeMemcachedClusters) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(memcachedclustersResource, c.ns, opts))

}

// Create takes the representation of a memcachedCluster and creates it.  Returns the server's representation of the memcachedCluster, and an error, if there is any.
func (c *FakeMemcachedClusters) Create(memcachedCluster *v1alpha1.MemcachedCluster) (result *v1alpha1.MemcachedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(memcachedclustersResource, c.ns, memcachedCluster), &v1alpha1.MemcachedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemcachedCluster), err
}

// Update takes the representation of a memcachedCluster and updates it. Returns the server's representation of the memcachedCluster, and an error, if there is any.
func (c *FakeMemcachedClusters) Update(memcachedCluster *v1alpha1.MemcachedCluster) (result *v1alpha1.MemcachedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(memcachedclustersResource, c.ns, memcachedCluster), &v1alpha1.MemcachedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemcachedCluster), err
}

// Delete takes name of the memcachedCluster and deletes it. Returns an error if one occurs.
func (c *FakeMemcachedClusters) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(memcachedclustersResource, c.ns, name), &v1alpha1.MemcachedCluster{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMemcachedClusters) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(memcachedclustersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MemcachedClusterList{})
	return err
}

// Patch applies the patch and returns the patched memcachedCluster.
func (c *FakeMemcachedClusters) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MemcachedCluster, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(memcachedclustersResource, c.ns, name, data, subresources...), &v1alpha1.MemcachedCluster{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MemcachedCluster), err
}
